# a very minimal declarative config file
_format_version: "2.1"
_transform: true
# This specifies the format version and is highly recommended.

# -----------------------------------------------------------------------------
# Part 1: Main Kong Configuration (replaces environment variables)
# -----------------------------------------------------------------------------
# These keys directly map to the KONG_ environment variables.
# KONG_ADMIN_GUI_URL -> admin_gui_url
# KONG_ADMIN_GUI_AUTH -> admin_gui_auth
# KONG_ADMIN_GUI_SESSION_CONF_FILE -> admin_gui_session_conf

admin_gui_url: "https://kong-manager.yourdomain.com"
admin_gui_auth: basic-auth
admin_gui_session_conf: /run/secrets/kong_gui_session_conf

# -----------------------------------------------------------------------------
# Part 2: Kong Service and Route for the Manager (replaces `curl` commands)
# -----------------------------------------------------------------------------
# This creates the proxy rule to expose the internal Manager UI.
services:
- name: kong-manager-service
  url: http://localhost:8002
  routes:
  - name: kong-manager-route
    hosts:
    - kong-manager.yourdomain.com
    protocols:
    - https
    strip_path: true

# -----------------------------------------------------------------------------
# Part 3: RBAC Configuration (Required for basic-auth in DB-less mode)
# -----------------------------------------------------------------------------
# You must define users and roles here. You cannot create them via the API.

# Define a role named 'super-admin' with full permissions.
rbac_roles:
- name: super-admin
  # The endpoint '*' gives access to everything.
  permissions:
    workspaces:
    - name: default
      endpoints:
      - "*"

# Define a user.
# !! IMPORTANT: Change the password below to something very strong.
rbac_users:
- name: manager_admin
  password: "a-very-strong-and-secret-password"
  
# Assign the 'super-admin' role to the 'manager_admin' user.
rbac_user_roles:
- user: manager_admin
  role: super-admin
